name: agro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.15.5
  path: ^1.8.3
  cached_network_image: ^3.3.1
  infinite_scroll_pagination: ^4.0.0
  timeago: ^3.7.0
  validators: ^3.0.0
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.7.0
  flutter_staggered_grid_view: ^0.7.0
  firebase_database: ^10.5.7
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/login_img.jpg
      - assets/gmail_logo.png
      - assets/logo_sl_white.png
      - assets/logo_sl_green.png
      - assets/logo_nego.png

